// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyComponent: typeof import('./src/components/MyComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('dz-starport')['Starport']
    StarportCarrier: typeof import('dz-starport')['StarportCarrier']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
  }
}
